server:
  port: 8012
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:test.db
    username: root
    password: ROOT

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        format_sql: true

field: Test

mail:
  #Simple properties
  hostname: host@mail.com
  port: 9000
  from: mailer@mail.com

  #List properties
  defaultRecipients[0]: admin@mail.com
  defaultRecipients[1]: owner@mail.com

  #Map Properties
  additionalHeaders:
    redelivery: true
    secure: true

  #Object properties
  credentials:
    username: john
    password: password
    authMethod: SHA1
logging:
  pattern:
  level:
    org.hibernate.orm.jdbc.bind: trace
